-- MySQL Script generated by MySQL Workbench
-- 08/13/17 00:47:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ppgprofile
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ppgprofile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppgprofile` ;
USE `ppgprofile` ;

-- -----------------------------------------------------
-- Table `ppgprofile`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `instituicao`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `conceitoMec` INT NOT NULL,
  `turno` VARCHAR(45) NULL,
  `campus` VARCHAR(45) NULL,
  `anoCriacao` YEAR NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `departamentoCurso`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`departamento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`usuario` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `siape` CHAR(7) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dataAdmissao` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`email` ASC),
  UNIQUE INDEX `siape_UNIQUE` (`siape` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `departamentoProfessor`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`email`)
    REFERENCES `ppgprofile`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`nome` ASC),
  CONSTRAINT `usuarioAdministrador`
    FOREIGN KEY (`nome`)
    REFERENCES `ppgprofile`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`entidadeFinanciadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`entidadeFinanciadora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`bolsaEstudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`bolsaEstudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `departamentoBolsaEstudo`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entidadeFinanciadora`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`entidadeFinanciadora` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(255) NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `crGraduacao` DOUBLE NOT NULL,
  `anoConclusaoGraduacao` YEAR NOT NULL,
  `semestreIngresso` CHAR(6) NOT NULL,
  `dedicacao` INT NOT NULL,
  `areaConhecimento` VARCHAR(255) NOT NULL,
  `titulo` INT NOT NULL,
  `cr` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cursoGraduacao`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`curso` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `curso`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`curso` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `orientador`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`professor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `coOrientador`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`professor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`defesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`defesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `aprovacao` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `aluno`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppgprofile`.`avaliacao_defesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppgprofile`.`avaliacao_defesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nota` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `defesa`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`defesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avaliador`
    FOREIGN KEY (`id`)
    REFERENCES `ppgprofile`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
